---
global:
  owner: luis.cazacu@keysight.com
  qsname: quickstart-cloudlens
  regions:
    - us-east-1
    - us-west-2
  reporting: true
tests:
  deploy-defaults:
    parameter_input: defaults-input.json
    regions:
      - us-east-1
      - us-west-2
    template_file: CloudLens-EastWind-QuickStart.template.json
  custom-ami:
    parameter_input: customami-input.json
    regions:
      - us-east-1
    template_file: CloudLens-EastWind-QuickStart.template.json
  dev-servername:
    parameter_input: dev-project-key-input.json
    regions:
      - us-east-1
    template_file: CloudLens-EastWind-QuickStart.template.json
  custom-vpc-subnet:
    parameter_input: custom-vpc-subnet-input.json
    regions:
      - us-east-1
    template_file: CloudLens-EastWind-QuickStart.template.json

