---
global:
  owner: luis.cazacu@keysight.com
  qsname: quickstart-cloudlens
  regions:
    - eu-west-1
    - us-east-1
    - us-west-2
  reporting: true
tests:
  deploy-defaults:
    parameter_input: defaults-input.json
    regions:
      - us-east-1
      - us-west-2
    template_file: CloudLens-EastWind-QuickStart.template.json
